import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

// ESLint 9 flat config. Replaces the legacy .eslintrc; lints the TS/TSX
// sources with the TypeScript, React Hooks, and React Refresh rule sets.
export default tseslint.config(
  // wailsjs/ is generated by `wails generate module` and is overwritten on
  // every build, so lint fixes there would not survive.
  { ignores: ['dist', 'node_modules', 'wailsjs', 'coverage'] },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // Underscore-prefixed bindings are the codebase's marker for a
      // deliberately unused parameter or an omitted destructured key.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Off, not warn: every current violation is a dependency array that was
      // trimmed on purpose, and "fixing" one changes when the effect re-runs.
      // Re-enable per-file once those effects have been audited individually.
      'react-hooks/exhaustive-deps': 'off',
      // React Compiler checks, which the recommended set gained in version 7.
      // The app does not use the compiler, and each current finding is code
      // whose rewrite would change when state updates or effects run. Enable
      // them one at a time with that review.
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/incompatible-library': 'off',
    },
  },
);
