//go:build darwin

package state

import (
	"syscall"
	"testing"
)

// TestReadPIDDomain_NamesTheBootAndNotTheKernelBinary is the regression pin for
// which sysctl this reads. kern.uuid is the Mach-O UUID of the running kernel,
// taken from the kernel image itself: every Mac booted from one kernel build
// reports the same value, so two of them sharing a source directory would each
// read the other's live PIDs as dead and take its lock. Only
// kern.bootsessionuuid is generated by the kernel at every boot.
func TestReadPIDDomain_NamesTheBootAndNotTheKernelBinary(t *testing.T) {
	domain, err := readPIDDomain()
	if err != nil {
		t.Fatalf("readPIDDomain failed: %v", err)
	}

	boot, err := syscall.Sysctl("kern.bootsessionuuid")
	if err != nil {
		t.Fatalf("read kern.bootsessionuuid: %v", err)
	}
	if domain != boot {
		t.Errorf("the PID domain is %q, want this boot session %q", domain, boot)
	}

	kernel, err := syscall.Sysctl("kern.uuid")
	if err != nil {
		t.Fatalf("read kern.uuid: %v", err)
	}
	if domain == kernel {
		t.Errorf("the PID domain is the kernel binary UUID %q, which every Mac running this kernel build reports", kernel)
	}
}
