// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllTransfers() {
  return window['go']['wailsapp']['App']['CancelAllTransfers']();
}

export function CancelLocalDirectoryRead() {
  return window['go']['wailsapp']['App']['CancelLocalDirectoryRead']();
}

export function CancelRun() {
  return window['go']['wailsapp']['App']['CancelRun']();
}

export function CancelTransfer(arg1) {
  return window['go']['wailsapp']['App']['CancelTransfer'](arg1);
}

export function CheckFolderExistsForUpload(arg1, arg2) {
  return window['go']['wailsapp']['App']['CheckFolderExistsForUpload'](arg1, arg2);
}

export function ClearCatalogCache() {
  return window['go']['wailsapp']['App']['ClearCatalogCache']();
}

export function ClearCompletedTransfers() {
  return window['go']['wailsapp']['App']['ClearCompletedTransfers']();
}

export function CreateRemoteFolder(arg1, arg2) {
  return window['go']['wailsapp']['App']['CreateRemoteFolder'](arg1, arg2);
}

export function DeleteRemoteItems(arg1) {
  return window['go']['wailsapp']['App']['DeleteRemoteItems'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['wailsapp']['App']['DeleteTemplate'](arg1);
}

export function GetAnalysisCodes(arg1) {
  return window['go']['wailsapp']['App']['GetAnalysisCodes'](arg1);
}

export function GetAppInfo() {
  return window['go']['wailsapp']['App']['GetAppInfo']();
}

export function GetAutomations() {
  return window['go']['wailsapp']['App']['GetAutomations']();
}

export function GetConfig() {
  return window['go']['wailsapp']['App']['GetConfig']();
}

export function GetCoreTypes() {
  return window['go']['wailsapp']['App']['GetCoreTypes']();
}

export function GetDaemonConfig() {
  return window['go']['wailsapp']['App']['GetDaemonConfig']();
}

export function GetDaemonLogs(arg1) {
  return window['go']['wailsapp']['App']['GetDaemonLogs'](arg1);
}

export function GetDaemonStatus() {
  return window['go']['wailsapp']['App']['GetDaemonStatus']();
}

export function GetDefaultConfigPath() {
  return window['go']['wailsapp']['App']['GetDefaultConfigPath']();
}

export function GetDefaultDownloadFolder() {
  return window['go']['wailsapp']['App']['GetDefaultDownloadFolder']();
}

export function GetFileLoggingSettings() {
  return window['go']['wailsapp']['App']['GetFileLoggingSettings']();
}

export function GetHistoricalJobRows(arg1) {
  return window['go']['wailsapp']['App']['GetHistoricalJobRows'](arg1);
}

export function GetHomeDirectory() {
  return window['go']['wailsapp']['App']['GetHomeDirectory']();
}

export function GetJobRows() {
  return window['go']['wailsapp']['App']['GetJobRows']();
}

export function GetJobsStats() {
  return window['go']['wailsapp']['App']['GetJobsStats']();
}

export function GetLocalFilesInfo(arg1) {
  return window['go']['wailsapp']['App']['GetLocalFilesInfo'](arg1);
}

export function GetLogFileLocation() {
  return window['go']['wailsapp']['App']['GetLogFileLocation']();
}

export function GetLogsDirectory() {
  return window['go']['wailsapp']['App']['GetLogsDirectory']();
}

export function GetMyJobsFolderID() {
  return window['go']['wailsapp']['App']['GetMyJobsFolderID']();
}

export function GetMyLibraryFolderID() {
  return window['go']['wailsapp']['App']['GetMyLibraryFolderID']();
}

export function GetRunHistory() {
  return window['go']['wailsapp']['App']['GetRunHistory']();
}

export function GetRunStatus() {
  return window['go']['wailsapp']['App']['GetRunStatus']();
}

export function GetServiceStatus() {
  return window['go']['wailsapp']['App']['GetServiceStatus']();
}

export function GetTransferStats() {
  return window['go']['wailsapp']['App']['GetTransferStats']();
}

export function GetTransferTasks() {
  return window['go']['wailsapp']['App']['GetTransferTasks']();
}

export function ListLocalDirectory(arg1) {
  return window['go']['wailsapp']['App']['ListLocalDirectory'](arg1);
}

export function ListLocalDirectoryEx(arg1, arg2) {
  return window['go']['wailsapp']['App']['ListLocalDirectoryEx'](arg1, arg2);
}

export function ListRemoteFolder(arg1) {
  return window['go']['wailsapp']['App']['ListRemoteFolder'](arg1);
}

export function ListRemoteFolderPage(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['ListRemoteFolderPage'](arg1, arg2, arg3);
}

export function ListRemoteLegacy(arg1, arg2) {
  return window['go']['wailsapp']['App']['ListRemoteLegacy'](arg1, arg2);
}

export function ListSavedTemplates() {
  return window['go']['wailsapp']['App']['ListSavedTemplates']();
}

export function LoadConfigFromPath(arg1) {
  return window['go']['wailsapp']['App']['LoadConfigFromPath'](arg1);
}

export function LoadJobFromJSON(arg1) {
  return window['go']['wailsapp']['App']['LoadJobFromJSON'](arg1);
}

export function LoadJobFromSGE(arg1) {
  return window['go']['wailsapp']['App']['LoadJobFromSGE'](arg1);
}

export function LoadJobsFromCSV(arg1) {
  return window['go']['wailsapp']['App']['LoadJobsFromCSV'](arg1);
}

export function LoadJobsFromJSON(arg1) {
  return window['go']['wailsapp']['App']['LoadJobsFromJSON'](arg1);
}

export function LoadTemplate(arg1) {
  return window['go']['wailsapp']['App']['LoadTemplate'](arg1);
}

export function OpenLogsDirectory() {
  return window['go']['wailsapp']['App']['OpenLogsDirectory']();
}

export function PauseDaemon() {
  return window['go']['wailsapp']['App']['PauseDaemon']();
}

export function PreviewCommandPatterns(arg1, arg2) {
  return window['go']['wailsapp']['App']['PreviewCommandPatterns'](arg1, arg2);
}

export function ResetRun() {
  return window['go']['wailsapp']['App']['ResetRun']();
}

export function ResumeDaemon() {
  return window['go']['wailsapp']['App']['ResumeDaemon']();
}

export function RetryTransfer(arg1) {
  return window['go']['wailsapp']['App']['RetryTransfer'](arg1);
}

export function SaveConfig() {
  return window['go']['wailsapp']['App']['SaveConfig']();
}

export function SaveConfigAs(arg1) {
  return window['go']['wailsapp']['App']['SaveConfigAs'](arg1);
}

export function SaveDaemonConfig(arg1) {
  return window['go']['wailsapp']['App']['SaveDaemonConfig'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['wailsapp']['App']['SaveFile'](arg1);
}

export function SaveJobToJSON(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveJobToJSON'](arg1, arg2);
}

export function SaveJobToSGE(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveJobToSGE'](arg1, arg2);
}

export function SaveJobsToCSV(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveJobsToCSV'](arg1, arg2);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveTemplate'](arg1, arg2);
}

export function ScanDirectory(arg1, arg2) {
  return window['go']['wailsapp']['App']['ScanDirectory'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['wailsapp']['App']['SelectDirectory'](arg1);
}

export function SelectDirectoryAndListFiles(arg1) {
  return window['go']['wailsapp']['App']['SelectDirectoryAndListFiles'](arg1);
}

export function SelectDirectoryRecursive(arg1) {
  return window['go']['wailsapp']['App']['SelectDirectoryRecursive'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['wailsapp']['App']['SelectFile'](arg1);
}

export function SelectMultipleFiles(arg1) {
  return window['go']['wailsapp']['App']['SelectMultipleFiles'](arg1);
}

export function SetFileLoggingEnabled(arg1) {
  return window['go']['wailsapp']['App']['SetFileLoggingEnabled'](arg1);
}

export function StartBulkRun(arg1) {
  return window['go']['wailsapp']['App']['StartBulkRun'](arg1);
}

export function StartBulkRunWithOptions(arg1, arg2) {
  return window['go']['wailsapp']['App']['StartBulkRunWithOptions'](arg1, arg2);
}

export function StartDaemon() {
  return window['go']['wailsapp']['App']['StartDaemon']();
}

export function StartFolderDownload(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['StartFolderDownload'](arg1, arg2, arg3);
}

export function StartFolderUpload(arg1, arg2) {
  return window['go']['wailsapp']['App']['StartFolderUpload'](arg1, arg2);
}

export function StartServiceElevated() {
  return window['go']['wailsapp']['App']['StartServiceElevated']();
}

export function StartSingleJob(arg1) {
  return window['go']['wailsapp']['App']['StartSingleJob'](arg1);
}

export function StartTransfers(arg1) {
  return window['go']['wailsapp']['App']['StartTransfers'](arg1);
}

export function StopDaemon() {
  return window['go']['wailsapp']['App']['StopDaemon']();
}

export function StopServiceElevated() {
  return window['go']['wailsapp']['App']['StopServiceElevated']();
}

export function TestAutoDownloadConnection(arg1) {
  return window['go']['wailsapp']['App']['TestAutoDownloadConnection'](arg1);
}

export function TestConnection() {
  return window['go']['wailsapp']['App']['TestConnection']();
}

export function TriggerDaemonScan() {
  return window['go']['wailsapp']['App']['TriggerDaemonScan']();
}

export function TriggerProfileRescan() {
  return window['go']['wailsapp']['App']['TriggerProfileRescan']();
}

export function UpdateConfig(arg1) {
  return window['go']['wailsapp']['App']['UpdateConfig'](arg1);
}

export function ValidateAutoDownloadSetup() {
  return window['go']['wailsapp']['App']['ValidateAutoDownloadSetup']();
}

export function ValidateJobSpec(arg1) {
  return window['go']['wailsapp']['App']['ValidateJobSpec'](arg1);
}
